// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnxiazinwdpyhviyjdwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJueGlhemlud2RweWh2aXlqZHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQyMjcsImV4cCI6MjA2NTM4MDIyN30.Z6jdozMX8QNLQbzZns2HzR3l3Lo18SuFeGooc3Or4Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);